In [1]:
# First we load the packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# I. Building the Dataset: Player Stats

In [2]:
# Read in salary data retrieved from Lahman's Database
Salary = pd.read_csv("../Data/Salaries.csv")

# Read in batting
Batting = pd.read_csv("../Data/Batting.csv")

### 1. Load the “Salaries” file, drop any missing values, create a variable for the natural log (ln) of player salary, and rename the column “yearID” as “SalYear”.

In [3]:
Salary = Salary.dropna() 
Salary.head()

   yearID teamID lgID   playerID  salary
0    1985    ATL   NL  barkele01  870000
1    1985    ATL   NL  bedrost01  550000
2    1985    ATL   NL  benedbr01  545000
3    1985    ATL   NL   campri01  633333
4    1985    ATL   NL  ceronri01  625000

In [4]:
Salary['lnSal'] = np.log(Salary['salary'])
Salary.head()

   yearID teamID lgID   playerID  salary      lnSal
0    1985    ATL   NL  barkele01  870000  13.676248
1    1985    ATL   NL  bedrost01  550000  13.217674
2    1985    ATL   NL  benedbr01  545000  13.208541
3    1985    ATL   NL   campri01  633333  13.358752
4    1985    ATL   NL  ceronri01  625000  13.345507

In [5]:
Salary = Salary.rename(columns = {'yearID':'SalYear'})

### 2. Create a copy of the “Salaries” dataframe called “Master”.

In [6]:
Master = Salary
Master

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
5         1985    ATL   NL  chambch01    800000  13.592367
6         1985    ATL   NL  dedmoje01    150000  11.918391
7         1985    ATL   NL  forstte01    483333  13.088461
8         1985    ATL   NL  garbege01    772000  13.556740
9         1985    ATL   NL  harpete01    250000  12.429216
10        1985    ATL   NL  hornebo01   1500000  14.220976
11        1985    ATL   NL  hubbagl01    455000  13.028053
12        1985    ATL   NL  mahleri01    407500  12.917796
13        1985    ATL   NL  mcmurcr01    275000  12.524526
14        1985    ATL   NL  mumphje01    775000  13.560618
15        1985    ATL   NL  murphda05   1625000  14.301018
16        1985    ATL   NL  oberkke01    616667  13.332084
17        1985    ATL   NL  perezpa01    450000  13.017003
18        1985    ATL   NL  perryge01    120000  11.695247
19        1985    ATL   NL  ramirra01    750000  13.527828
20        1985    ATL   NL  suttebr01   1354167  14.118697
21        1985    ATL   NL  washicl01    800000  13.592367
22        1985    BAL   AL  boddimi01    625000  13.345507
23        1985    BAL   AL  dauerri01    480000  13.081541
24        1985    BAL   AL  davisst02    437500  12.988832
25        1985    BAL   AL  dempsri01    512500  13.147056
26        1985    BAL   AL  dwyerji01    375000  12.834681
27        1985    BAL   AL  flanami01    641667  13.371825
28        1985    BAL   AL   fordda01    450000  13.017003
29        1985    BAL   AL  grosswa01    483333  13.088461
...        ...    ...  ...        ...       ...        ...
26398     2016    TOR   AL  stromma01    515900  13.153668
26399     2016    TOR   AL  tholejo01    800000  13.592367
26400     2016    TOR   AL  travide01    511200  13.144516
26401     2016    TOR   AL  tulowtr01  20000000  16.811243
26402     2016    WAS   NL  barreaa01    519400  13.160430
26403     2016    WAS   NL  belisma01   1250000  14.038654
26404     2016    WAS   NL   drewst01   3000000  14.914123
26405     2016    WAS   NL  espinda01   2875000  14.871563
26406     2016    WAS   NL  gonzagi01  12100000  16.308716
26407     2016    WAS   NL  harpebr03   5000000  15.424948
26408     2016    WAS   NL  heisech01   1250000  14.038654
26409     2016    WAS   NL  kellesh01   4000000  15.201805
26410     2016    WAS   NL  lobatjo01   1387500  14.143014
26411     2016    WAS   NL  murphda08   8000000  15.894952
26412     2016    WAS   NL  papeljo01  10936574  16.207623
26413     2016    WAS   NL  perezol01   3000000  14.914123
26414     2016    WAS   NL  petityu01   2500000  14.731801
26415     2016    WAS   NL  ramoswi01   5350000  15.492607
26416     2016    WAS   NL  rendoan01   2800000  14.845130
26417     2016    WAS   NL  reverbe01   6250000  15.648092
26418     2016    WAS   NL  riverfe01    516100  13.154056
26419     2016    WAS   NL  roarkta01    543400  13.205601
26420     2016    WAS   NL  robincl01    534900  13.189835
26421     2016    WAS   NL   rossjo01    514400  13.150756
26422     2016    WAS   NL  scherma01  22142857  16.913026
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26428 rows x 6 columns]

### 3. Load the batting data and sum data across stints.

In [7]:
Batting = Batting.groupby(['playerID','yearID']).sum()
Batting.reset_index(inplace=True)
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,2004,1,11,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,2006,1,45,2,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,2007,1,25,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,2008,1,47,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,2009,1,73,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,aardsda01,2010,1,53,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
6,aardsda01,2012,1,1,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
7,aardsda01,2013,1,43,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,aardsda01,2015,1,33,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
9,aaronha01,1954,1,122,468,58,131,27,6,13,69.0,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0
10,aaronha01,1955,1,153,602,105,189,37,9,27,106.0,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0
11,aaronha01,1956,1,153,609,106,200,34,14,26,92.0,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0
12,aaronha01,1957,1,151,615,118,198,27,6,44,132.0,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0
13,aaronha01,1958,1,153,601,109,196,34,4,30,95.0,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0
14,aaronha01,1959,1,154,629,116,223,46,7,39,123.0,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0
15,aaronha01,1960,1,153,590,102,172,20,11,40,126.0,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0
16,aaronha01,1961,1,155,603,115,197,39,10,34,120.0,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0
17,aaronha01,1962,1,156,592,127,191,28,6,45,128.0,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0
18,aaronha01,1963,1,161,631,121,201,29,4,44,130.0,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0
19,aaronha01,1964,1,145,570,103,187,30,2,24,95.0,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0
20,aaronha01,1965,1,150,570,109,181,40,1,32,89.0,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0
21,aaronha01,1966,1,158,603,117,168,23,1,44,127.0,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0
22,aaronha01,1967,1,155,600,113,184,37,3,39,109.0,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0
23,aaronha01,1968,1,160,606,84,174,33,4,29,86.0,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0
24,aaronha01,1969,1,147,547,100,164,30,3,44,97.0,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0
25,aaronha01,1970,1,150,516,103,154,26,1,38,118.0,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0
26,aaronha01,1971,1,139,495,95,162,22,3,47,118.0,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0
27,aaronha01,1972,1,129,449,75,119,10,0,34,77.0,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0
28,aaronha01,1973,1,120,392,84,118,12,1,40,96.0,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0
29,aaronha01,1974,1,112,340,47,91,16,0,20,69.0,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95220,zupcibo01,1991,1,18,25,3,4,0,0,1,3.0,0.0,0.0,1,6.0,0.0,0.0,1.0,0.0,0.0
95221,zupcibo01,1992,1,124,392,46,108,19,1,3,43.0,2.0,2.0,25,60.0,1.0,4.0,7.0,4.0,6.0
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0
95223,zupcibo01,1994,3,36,92,10,18,4,1,1,8.0,0.0,1.0,4,17.0,0.0,0.0,4.0,1.0,2.0
95224,zupofr01,1957,1,10,12,2,1,0,0,0,0.0,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0
95225,zupofr01,1958,1,1,2,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
95226,zupofr01,1961,1,5,4,1,2,1,0,0,0.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
95227,zuvelpa01,1982,1,2,1,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95228,zuvelpa01,1983,1,3,5,0,0,0,0,0,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0
95229,zuvelpa01,1984,1,11,25,2,5,1,0,0,1.0,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0
95230,zuvelpa01,1985,1,81,190,16,48,8,1,0,4.0,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0
95231,zuvelpa01,1986,1,21,48,2,4,1,0,0,2.0,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0
95232,zuvelpa01,1987,1,14,34,2,6,0,0,0,0.0,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0
95233,zuvelpa01,1988,1,51,130,9,30,5,1,0,7.0,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0
95234,zuvelpa01,1989,1,24,58,10,16,2,0,2,6.0,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0
95235,zuvelpa01,1991,1,2,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95236,zuverge01,1951,1,16,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95237,zuverge01,1952,1,2,0,1,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95238,zuverge01,1954,3,37,66,2,9,1,0,0,3.0,0.0,1.0,1,15.0,0.0,0.0,9.0,0.0,2.0
95239,zuverge01,1955,3,42,27,1,5,1,0,0,0.0,0.0,0.0,1,7.0,0.0,0.0,1.0,0.0,1.0
95240,zuverge01,1956,1,62,17,0,2,0,0,0,2.0,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0
95241,zuverge01,1957,1,56,23,1,3,0,0,0,0.0,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0
95242,zuverge01,1958,1,45,9,0,2,0,1,0,2.0,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0
95243,zuverge01,1959,1,6,0,0,0,0,0,0,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0
95244,zwilldu01,1910,1,27,87,7,16,5,0,0,5.0,1.0,0.0,11,0.0,0.0,1.0,1.0,0.0,0.0
95245,zwilldu01,1914,1,154,592,91,185,38,8,16,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
95246,zwilldu01,1915,1,150,548,65,157,32,7,13,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
95247,zwilldu01,1916,1,35,53,4,6,1,0,1,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0
95248,zychto01,2015,1,13,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95249,zychto01,2016,1,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

### 4. Subset batting data to only include batting seasons (yearID) 1998-2006 and players with at least 130AB

In [8]:
Batting = Batting[(Batting.yearID >= 1998) & (Batting.yearID <= 2006) & (Batting.AB >= 130)].copy()
display(Batting)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0
144,abercre01,2006,1,111,255,39,54,12,2,5,24.0,6.0,5.0,18,78.0,2.0,3.0,4.0,1.0,2.0
148,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0
149,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0
195,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0
196,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0
197,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0
198,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0
199,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0
200,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0
201,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0
202,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0
203,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0
437,adamsru01,2005,1,139,481,68,123,27,5,8,63.0,11.0,2.0,50,57.0,1.0,3.0,3.0,8.0,5.0
438,adamsru01,2006,1,90,251,31,55,14,1,3,28.0,1.0,2.0,22,41.0,0.0,1.0,3.0,3.0,5.0
567,agbaybe01,1999,1,101,276,42,79,18,3,14,42.0,6.0,4.0,32,60.0,4.0,3.0,0.0,3.0,8.0
568,agbaybe01,2000,1,119,350,59,101,19,1,15,60.0,5.0,5.0,54,68.0,2.0,7.0,0.0,3.0,6.0
569,agbaybe01,2001,1,91,296,28,82,14,2,6,27.0,4.0,5.0,36,73.0,0.0,5.0,1.0,1.0,11.0
570,agbaybe01,2002,3,61,154,15,35,6,0,4,27.0,1.0,0.0,16,40.0,1.0,0.0,0.0,1.0,5.0
868,alexama02,1998,1,108,264,34,60,10,1,5,25.0,4.0,1.0,18,66.0,1.0,1.0,5.0,1.0,6.0
869,alexama02,1999,1,90,177,17,48,11,2,0,15.0,4.0,0.0,10,38.0,0.0,0.0,1.0,1.0,1.0
870,alexama02,2000,1,101,194,30,41,4,3,4,19.0,2.0,0.0,13,41.0,0.0,0.0,2.0,0.0,0.0
918,alfoned01,1998,1,144,557,94,155,28,2,17,78.0,8.0,3.0,65,77.0,1.0,3.0,2.0,3.0,11.0
919,alfoned01,1999,1,158,628,123,191,41,1,27,108.0,9.0,2.0,85,85.0,2.0,3.0,1.0,9.0,14.0
920,alfoned01,2000,1,150,544,109,176,40,2,25,94.0,3.0,2.0,95,70.0,1.0,5.0,0.0,6.0,12.0
921,alfoned01,2001,1,124,457,64,111,22,0,17,49.0,5.0,0.0,51,62.0,0.0,5.0,1.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94628,younger01,2004,1,104,344,55,99,25,2,1,27.0,14.0,9.0,43,28.0,0.0,8.0,4.0,3.0,9.0
94629,younger01,2005,1,56,142,22,39,9,0,2,12.0,7.0,6.0,18,12.0,0.0,0.0,3.0,0.0,4.0
94630,younger01,2006,3,60,138,20,28,6,1,3,15.0,8.0,2.0,14,17.0,1.0,2.0,2.0,3.0,7.0
94689,youngke01,1998,1,159,592,88,160,40,2,27,108.0,15.0,7.0,44,127.0,1.0,11.0,0.0,9.0,20.0
94690,youngke01,1999,1,156,584,103,174,41,6,26,106.0,22.0,10.0,75,124.0,5.0,12.0,0.0,4.0,13.0
94691,youngke01,2000,1,132,496,77,128,27,0,20,88.0,8.0,3.0,32,96.0,1.0,8.0,0.0,5.0,15.0
94692,youngke01,2001,1,142,449,53,104,33,0,14,65.0,15.0,11.0,42,119.0,3.0,11.0,0.0,5.0,17.0
94693,youngke01,2002,1,146,468,60,115,26,1,16,51.0,4.0,6.0,50,101.0,2.0,4.0,0.0,3.0,13.0
94719,youngmi02,2001,1,106,386,57,96,18,4,11,49.0,3.0,1.0,26,91.0,0.0,3.0,9.0,5.0,9.0
94720,youngmi02,2002,1,156,573,77,150,26,8,9,62.0,6.0,7.0,41,112.0,1.0,0.0,13.0,6.0,14.0
94721,youngmi02,2003,1,160,666,106,204,33,9,14,72.0,13.0,2.0,36,103.0,1.0,1.0,3.0,7.0,14.0
94722,youngmi02,2004,1,160,690,114,216,33,9,22,99.0,12.0,3.0,44,89.0,1.0,1.0,0.0,4.0,11.0
94723,youngmi02,2005,1,159,668,114,221,40,5,24,91.0,5.0,2.0,58,91.0,0.0,3.0,0.0,3.0,20.0
94724,youngmi02,2006,1,162,691,93,217,52,3,14,103.0,7.0,3.0,48,96.0,0.0,1.0,0.0,8.0,27.0
94937,zaungr01,1998,1,106,298,19,56,12,2,5,29.0,5.0,2.0,35,52.0,2.0,1.0,2.0,2.0,7.0
94939,zaungr01,2000,1,83,234,36,64,11,0,7,33.0,7.0,3.0,43,34.0,3.0,3.0,0.0,2.0,4.0
94941,zaungr01,2002,1,76,185,18,41,7,1,3,24.0,1.0,0.0,12,36.0,1.0,2.0,2.0,1.0,4.0
94942,zaungr01,2003,3,74,166,15,38,8,0,4,21.0,1.0,1.0,19,21.0,0.0,1.0,1.0,2.0,5.0
94943,zaungr01,2004,1,107,338,46,91,24,0,6,36.0,0.0,2.0,47,61.0,3.0,6.0,0.0,1.0,7.0
94944,zaungr01,2005,1,133,434,61,109,18,1,11,61.0,2.0,3.0,73,70.0,2.0,0.0,0.0,5.0,11.0
94945,zaungr01,2006,1,99,290,39,79,19,0,12,40.0,0.0,2.0,41,42.0,3.0,3.0,0.0,5.0,10.0
94984,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0
94985,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0
94986,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0
94987,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0

### 5. Calculate PA, OBP, SLG, and batting average

In [9]:
Batting['PA'] = Batting['AB'] + Batting['BB'] + Batting['HBP'] + Batting['SH'] + Batting['SF']

Batting['OBP'] = (Batting['H'] + Batting['BB'] + Batting['HBP'])/(Batting['AB'] + Batting['BB']
                                                                  + Batting['HBP'] + Batting['SF'])

Batting['SLG'] = ((Batting['H'] - Batting['Doubles'] - Batting['Triples'] - Batting['HR']) 
                  + 2*Batting['Doubles'] + 3*Batting['Triples'] + 4*Batting['HR'])/Batting['AB']

Batting['BATAVG'] = Batting['H']/Batting['AB']

### 6. Create SalYear variable to create one year lag between batting performance and salary

In [10]:
Batting['SalYear'] = Batting['yearID'] + 1 
display(Batting)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BATAVG,SalYear
98,abbotje01,1998,1,89,244,33,68,14,1,12,...,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689,1999
100,abbotje01,2000,1,80,215,31,59,15,1,3,...,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419,2001
117,abbotku01,1998,3,77,194,26,51,13,1,5,...,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887,1999
118,abbotku01,1999,1,96,286,41,78,17,2,8,...,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727,2000
119,abbotku01,2000,1,79,157,22,34,7,1,6,...,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561,2001
144,abercre01,2006,1,111,255,39,54,12,2,5,...,2.0,3.0,4.0,1.0,2.0,281.0,0.270758,0.333333,0.211765,2007
148,abernbr01,2001,1,79,304,43,82,17,1,5,...,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,0.269737,2002
149,abernbr01,2002,1,117,463,46,112,18,4,2,...,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,0.241901,2003
195,abreubo01,1998,1,151,497,68,155,29,6,17,...,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,0.311871,1999
196,abreubo01,1999,1,152,546,118,183,35,11,20,...,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,0.335165,2000
197,abreubo01,2000,1,154,576,103,182,42,10,25,...,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,0.315972,2001
198,abreubo01,2001,1,162,588,118,170,48,4,31,...,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,0.289116,2002
199,abreubo01,2002,1,157,572,102,176,50,6,20,...,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,0.307692,2003
200,abreubo01,2003,1,158,577,99,173,35,1,20,...,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,0.299827,2004
201,abreubo01,2004,1,159,574,118,173,47,1,30,...,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,0.301394,2005
202,abreubo01,2005,1,162,588,104,168,37,1,24,...,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,0.285714,2006
203,abreubo01,2006,3,156,548,98,163,41,2,15,...,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,0.297445,2007
437,adamsru01,2005,1,139,481,68,123,27,5,8,...,1.0,3.0,3.0,8.0,5.0,545.0,0.324723,0.382536,0.255717,2006
438,adamsru01,2006,1,90,251,31,55,14,1,3,...,0.0,1.0,3.0,3.0,5.0,280.0,0.281588,0.318725,0.219124,2007
567,agbaybe01,1999,1,101,276,42,79,18,3,14,...,4.0,3.0,0.0,3.0,8.0,314.0,0.363057,0.525362,0.286232,2000
568,agbaybe01,2000,1,119,350,59,101,19,1,15,...,2.0,7.0,0.0,3.0,6.0,414.0,0.391304,0.477143,0.288571,2001
569,agbaybe01,2001,1,91,296,28,82,14,2,6,...,0.0,5.0,1.0,1.0,11.0,339.0,0.363905,0.398649,0.277027,2002
570,agbaybe01,2002,3,61,154,15,35,6,0,4,...,1.0,0.0,0.0,1.0,5.0,171.0,0.298246,0.344156,0.227273,2003
868,alexama02,1998,1,108,264,34,60,10,1,5,...,1.0,1.0,5.0,1.0,6.0,289.0,0.278169,0.329545,0.227273,1999
869,alexama02,1999,1,90,177,17,48,11,2,0,...,0.0,0.0,1.0,1.0,1.0,189.0,0.308511,0.355932,0.271186,2000
870,alexama02,2000,1,101,194,30,41,4,3,4,...,0.0,0.0,2.0,0.0,0.0,209.0,0.260870,0.324742,0.211340,2001
918,alfoned01,1998,1,144,557,94,155,28,2,17,...,1.0,3.0,2.0,3.0,11.0,630.0,0.355096,0.427289,0.278276,1999
919,alfoned01,1999,1,158,628,123,191,41,1,27,...,2.0,3.0,1.0,9.0,14.0,726.0,0.384828,0.501592,0.304140,2000
920,alfoned01,2000,1,150,544,109,176,40,2,25,...,1.0,5.0,0.0,6.0,12.0,650.0,0.424615,0.542279,0.323529,2001
921,alfoned01,2001,1,124,457,64,111,22,0,17,...,0.0,5.0,1.0,5.0,7.0,519.0,0.322394,0.402626,0.242888,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94628,younger01,2004,1,104,344,55,99,25,2,1,...,0.0,8.0,4.0,3.0,9.0,402.0,0.376884,0.380814,0.287791,2005
94629,younger01,2005,1,56,142,22,39,9,0,2,...,0.0,0.0,3.0,0.0,4.0,163.0,0.356250,0.380282,0.274648,2006
94630,younger01,2006,3,60,138,20,28,6,1,3,...,1.0,2.0,2.0,3.0,7.0,159.0,0.280255,0.326087,0.202899,2007
94689,youngke01,1998,1,159,592,88,160,40,2,27,...,1.0,11.0,0.0,9.0,20.0,656.0,0.327744,0.481419,0.270270,1999
94690,youngke01,1999,1,156,584,103,174,41,6,26,...,5.0,12.0,0.0,4.0,13.0,675.0,0.386667,0.522260,0.297945,2000
94691,youngke01,2000,1,132,496,77,128,27,0,20,...,1.0,8.0,0.0,5.0,15.0,541.0,0.310536,0.433468,0.258065,2001
94692,youngke01,2001,1,142,449,53,104,33,0,14,...,3.0,11.0,0.0,5.0,17.0,507.0,0.309665,0.398664,0.231626,2002
94693,youngke01,2002,1,146,468,60,115,26,1,16,...,2.0,4.0,0.0,3.0,13.0,525.0,0.321905,0.408120,0.245726,2003
94719,youngmi02,2001,1,106,386,57,96,18,4,11,...,0.0,3.0,9.0,5.0,9.0,429.0,0.297619,0.401554,0.248705,2002
94720,youngmi02,2002,1,156,573,77,150,26,8,9,...,1.0,0.0,13.0,6.0,14.0,633.0,0.308065,0.382199,0.261780,2003
94721,youngmi02,2003,1,160,666,106,204,33,9,14,...,1.0,1.0,3.0,7.0,14.0,713.0,0.339437,0.445946,0.306306,2004
94722,youngmi02,2004,1,160,690,114,216,33,9,22,...,1.0,1.0,0.0,4.0,11.0,739.0,0.353180,0.482609,0.313043,2005
94723,youngmi02,2005,1,159,668,114,221,40,5,24,...,0.0,3.0,0.0,3.0,20.0,732.0,0.385246,0.513473,0.330838,2006
94724,youngmi02,2006,1,162,691,93,217,52,3,14,...,0.0,1.0,0.0,8.0,27.0,748.0,0.355615,0.458755,0.314038,2007
94937,zaungr01,1998,1,106,298,19,56,12,2,5,...,2.0,1.0,2.0,2.0,7.0,338.0,0.273810,0.291946,0.187919,1999
94939,zaungr01,2000,1,83,234,36,64,11,0,7,...,3.0,3.0,0.0,2.0,4.0,282.0,0.390071,0.410256,0.273504,2001
94941,zaungr01,2002,1,76,185,18,41,7,1,3,...,1.0,2.0,2.0,1.0,4.0,202.0,0.275000,0.318919,0.221622,2003
94942,zaungr01,2003,3,74,166,15,38,8,0,4,...,0.0,1.0,1.0,2.0,5.0,189.0,0.308511,0.349398,0.228916,2004
94943,zaungr01,2004,1,107,338,46,91,24,0,6,...,3.0,6.0,0.0,1.0,7.0,392.0,0.367347,0.393491,0.269231,2005
94944,zaungr01,2005,1,133,434,61,109,18,1,11,...,2.0,0.0,0.0,5.0,11.0,512.0,0.355469,0.373272,0.251152,2006
94945,zaungr01,2006,1,99,290,39,79,19,0,12,...,3.0,3.0,0.0,5.0,10.0,339.0,0.362832,0.462069,0.272414,2007
94984,zeileto01,1998,6,158,572,85,155,32,3,19,...,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,0.270979,1999
94985,zeileto01,1999,1,156,588,80,172,41,1,24,...,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,0.292517,2000
94986,zeileto01,2000,1,153,544,67,146,36,3,22,...,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382,2001
94987,zeileto01,2001,1,151,531,66,141,25,1,10,...,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537,2002
94988,zeileto01,2002,1,144,506,61,138,23,0,18,...,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727,2003
94989,zeileto01,2003,3,100,299,40,68,10,2,11,...,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425,2004
94990,zeileto01,2004,1,137,348,30,81,16,0,9,...,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759,2005
95105,zimmery01,2006,1,157,614,84,176,47,3,20,...,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645,2007
95170,zobribe01,2006,1,52,183,10,41,6,2,2,...,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044,2007

### 7. Merge batting data and master data.

In [11]:
# carrying out the merge
Master = pd.merge(Batting, Master, on=['SalYear', 'playerID'])
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,GIDP,PA,OBP,SLG,BATAVG,SalYear,teamID,lgID,salary,lnSal
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685
5,abernbr01,2001,1,79,304,43,82,17,1,5,...,3.0,335.0,0.328313,0.381579,0.269737,2002,TBA,AL,215000,12.278393
6,abernbr01,2002,1,117,463,46,112,18,4,2,...,8.0,504.0,0.288306,0.311015,0.241901,2003,TBA,AL,300000,12.611538
7,abreubo01,1998,1,151,497,68,155,29,6,17,...,6.0,589.0,0.408547,0.496982,0.311871,1999,PHI,NL,400000,12.899220
8,abreubo01,1999,1,152,546,118,183,35,11,20,...,13.0,662.0,0.445619,0.549451,0.335165,2000,PHI,NL,2933333,14.891650
9,abreubo01,2000,1,154,576,103,182,42,10,25,...,12.0,680.0,0.416176,0.553819,0.315972,2001,PHI,NL,4983000,15.421543
10,abreubo01,2001,1,162,588,118,170,48,4,31,...,13.0,704.0,0.393466,0.542517,0.289116,2002,PHI,NL,6333333,15.661337
11,abreubo01,2002,1,157,572,102,176,50,6,20,...,11.0,685.0,0.413139,0.520979,0.307692,2003,PHI,NL,9100000,16.023785
12,abreubo01,2003,1,158,577,99,173,35,1,20,...,13.0,695.0,0.408633,0.467938,0.299827,2004,PHI,NL,10600000,16.176365
13,abreubo01,2004,1,159,574,118,173,47,1,30,...,5.0,713.0,0.427770,0.543554,0.301394,2005,PHI,NL,13100000,16.388123
14,abreubo01,2005,1,162,588,104,168,37,1,24,...,7.0,719.0,0.404729,0.474490,0.285714,2006,PHI,NL,13600000,16.425580
15,abreubo01,2006,3,156,548,98,163,41,2,15,...,13.0,686.0,0.423977,0.461679,0.297445,2007,NYA,AL,15000000,16.523561
16,adamsru01,2005,1,139,481,68,123,27,5,8,...,5.0,545.0,0.324723,0.382536,0.255717,2006,TOR,AL,343000,12.745486
17,agbaybe01,1999,1,101,276,42,79,18,3,14,...,8.0,314.0,0.363057,0.525362,0.286232,2000,NYN,NL,220000,12.301383
18,agbaybe01,2000,1,119,350,59,101,19,1,15,...,6.0,414.0,0.391304,0.477143,0.288571,2001,NYN,NL,260000,12.468437
19,agbaybe01,2001,1,91,296,28,82,14,2,6,...,11.0,339.0,0.363905,0.398649,0.277027,2002,COL,NL,600000,13.304685
20,alexama02,1998,1,108,264,34,60,10,1,5,...,6.0,289.0,0.278169,0.329545,0.227273,1999,CHN,NL,475000,13.071070
21,alexama02,1999,1,90,177,17,48,11,2,0,...,1.0,189.0,0.308511,0.355932,0.271186,2000,BOS,AL,612500,13.325304
22,alfoned01,1998,1,144,557,94,155,28,2,17,...,11.0,630.0,0.355096,0.427289,0.278276,1999,NYN,NL,2800000,14.845130
23,alfoned01,1999,1,158,628,123,191,41,1,27,...,14.0,726.0,0.384828,0.501592,0.304140,2000,NYN,NL,4225000,15.256530
24,alfoned01,2000,1,150,544,109,176,40,2,25,...,12.0,650.0,0.424615,0.542279,0.323529,2001,NYN,NL,5750000,15.564710
25,alfoned01,2001,1,124,457,64,111,22,0,17,...,7.0,519.0,0.322394,0.402626,0.242888,2002,NYN,NL,6200000,15.640060
26,alfoned01,2002,1,135,490,78,151,26,0,16,...,5.0,562.0,0.391459,0.459184,0.308163,2003,SFN,NL,4000000,15.201805
27,alfoned01,2003,1,142,514,56,133,25,2,13,...,14.0,586.0,0.334477,0.391051,0.258755,2004,SFN,NL,6500000,15.687313
28,alfoned01,2004,1,139,519,66,150,26,1,11,...,15.0,576.0,0.350174,0.406551,0.289017,2005,SFN,NL,7500000,15.830414
29,alfoned01,2005,1,109,368,36,102,17,1,2,...,11.0,402.0,0.326683,0.345109,0.277174,2006,LAA,AL,8000000,15.894952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3084,younger01,2000,1,153,607,98,180,40,2,6,...,12.0,690.0,0.367496,0.398682,0.296540,2001,CHN,NL,4500000,15.319588
3085,younger01,2001,1,149,603,98,168,43,4,6,...,15.0,672.0,0.333333,0.393035,0.278607,2002,MIL,NL,2000000,14.508658
3086,younger01,2002,1,138,496,57,139,29,3,3,...,14.0,553.0,0.337615,0.368952,0.280242,2003,MIL,NL,2000000,14.508658
3087,younger01,2003,3,135,475,80,119,20,1,15,...,12.0,541.0,0.335807,0.391579,0.250526,2004,TEX,AL,1000000,13.815511
3088,younger01,2004,1,104,344,55,99,25,2,1,...,9.0,402.0,0.376884,0.380814,0.287791,2005,SDN,NL,850000,13.652992
3089,younger01,2005,1,56,142,22,39,9,0,2,...,4.0,163.0,0.356250,0.380282,0.274648,2006,SDN,NL,700000,13.458836
3090,youngke01,1998,1,159,592,88,160,40,2,27,...,20.0,656.0,0.327744,0.481419,0.270270,1999,PIT,NL,2100000,14.557448
3091,youngke01,1999,1,156,584,103,174,41,6,26,...,13.0,675.0,0.386667,0.522260,0.297945,2000,PIT,NL,5625000,15.542732
3092,youngke01,2000,1,132,496,77,128,27,0,20,...,15.0,541.0,0.310536,0.433468,0.258065,2001,PIT,NL,6125000,15.627889
3093,youngke01,2001,1,142,449,53,104,33,0,14,...,17.0,507.0,0.309665,0.398664,0.231626,2002,PIT,NL,5625000,15.542732
3094,youngke01,2002,1,146,468,60,115,26,1,16,...,13.0,525.0,0.321905,0.408120,0.245726,2003,PIT,NL,6625000,15.706361
3095,youngmi02,2001,1,106,386,57,96,18,4,11,...,9.0,429.0,0.297619,0.401554,0.248705,2002,TEX,AL,250000,12.429216
3096,youngmi02,2002,1,156,573,77,150,26,8,9,...,14.0,633.0,0.308065,0.382199,0.261780,2003,TEX,AL,415000,12.936034
3097,youngmi02,2003,1,160,666,106,204,33,9,14,...,14.0,713.0,0.339437,0.445946,0.306306,2004,TEX,AL,450000,13.017003
3098,youngmi02,2004,1,160,690,114,216,33,9,22,...,11.0,739.0,0.353180,0.482609,0.313043,2005,TEX,AL,2575000,14.761360
3099,youngmi02,2005,1,159,668,114,221,40,5,24,...,20.0,732.0,0.385246,0.513473,0.330838,2006,TEX,AL,3075000,14.938815
3100,youngmi02,2006,1,162,691,93,217,52,3,14,...,27.0,748.0,0.355615,0.458755,0.314038,2007,TEX,AL,3575000,15.089476
3101,zaungr01,1998,1,106,298,19,56,12,2,5,...,7.0,338.0,0.273810,0.291946,0.187919,1999,TEX,AL,450000,13.017003
3102,zaungr01,2000,1,83,234,36,64,11,0,7,...,4.0,282.0,0.390071,0.410256,0.273504,2001,KCA,AL,1150000,13.955273
3103,zaungr01,2002,1,76,185,18,41,7,1,3,...,4.0,202.0,0.275000,0.318919,0.221622,2003,HOU,NL,1200000,13.997832
3104,zaungr01,2004,1,107,338,46,91,24,0,6,...,7.0,392.0,0.367347,0.393491,0.269231,2005,TOR,AL,950000,13.764217
3105,zaungr01,2005,1,133,434,61,109,18,1,11,...,11.0,512.0,0.355469,0.373272,0.251152,2006,TOR,AL,1000000,13.815511
3106,zaungr01,2006,1,99,290,39,79,19,0,12,...,10.0,339.0,0.362832,0.462069,0.272414,2007,TOR,AL,3500000,15.068274
3107,zeileto01,1998,6,158,572,85,155,32,3,19,...,12.0,653.0,0.349693,0.437063,0.270979,1999,TEX,AL,3200000,14.978661
3108,zeileto01,1999,1,156,588,80,172,41,1,24,...,20.0,656.0,0.354198,0.488095,0.292517,2000,NYN,NL,4333333,15.281848
3109,zeileto01,2000,1,153,544,67,146,36,3,22,...,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323
3110,zeileto01,2001,1,151,531,66,141,25,1,10,...,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323
3111,zeileto01,2002,1,144,506,61,138,23,0,18,...,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976
3112,zeileto01,2003,3,100,299,40,68,10,2,11,...,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511
3113,zobribe01,2006,1,52,183,10,41,6,2,2,...,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834

In [17]:
AvgSalary = Master[Master['SalYear'] == 1999]['salary'].mean() 
AvgSalary

2223975.2028169013

In [18]:
AvgOBPSLG = Master.groupby(['yearID'])[['OBP', 'SLG']].mean() 
AvgOBPSLG

             OBP       SLG
yearID
1998    0.337745  0.423344
1999    0.349470  0.442120
2000    0.348212  0.443840
2001    0.335789  0.433420
2002    0.335490  0.426230
2003    0.337403  0.430938
2004    0.341663  0.440307
2005    0.335947  0.428867
2006    0.342937  0.443275

In [22]:
HRPlayer = Master.groupby(['playerID'])[['HR']].sum() 
HRPlayer['HR'].max()

400

# II. Building the Dataset: Player Info

In [23]:
# Read in People data retrieved from Lahman's Database
People = pd.read_csv("../Data/People.csv")

# Read in player appearance data retrieved from Lahman's Database
Appearances = pd.read_csv("../Data/Appearances.csv")

### 1. Read in “People” data and extract the player’s debut year

In [25]:
# extracting the first four characters

Debut['debutyr'] = Debut['debut'].astype(str).str[0:4]
Debut.head()

    playerID       debut debutyr
0  aardsda01  2004-04-06    2004
1  aaronha01  1954-04-13    1954
2  aaronto01  1962-04-10    1962
3   aasedo01  1977-07-26    1977
4   abadan01  2001-09-10    2001

In [26]:
Debut = Debut[['playerID','debutyr']]

display(Debut)

        playerID debutyr
0      aardsda01    2004
1      aaronha01    1954
2      aaronto01    1962
3       aasedo01    1977
4       abadan01    2001
5       abadfe01    2010
6      abadijo01    1875
7      abbated01    1897
8      abbeybe01    1892
9      abbeych01    1893
10     abbotda01    1890
11     abbotfr01    1903
12     abbotgl01    1973
13     abbotje01    1997
14     abbotji01    1989
15     abbotku01    1993
16     abbotky01    1991
17     abbotod01    1910
18     abbotpa01    1990
19      aberal01    1950
20     abercda01    1871
21     abercre01    2006
22     abernbi01    1952
23     abernbr01    2001
24     abernte01    1942
25     abernte02    1955
26     abernwo01    1946
27     aberscl01    1947
28     ablesha01    1905
29     abnersh01    1987
...          ...     ...
19340  zimmejo02    2009
19341  zimmero01    1945
19342  zimmery01    2005
19343   zinkch01    2008
19344   zinkwa01    1921
19345   zinnfr01    1888
19346   zinngu01    1911
19347   zinnji01    1919
19348  zinsebi01    1944
19349  zinteal01    2002
19350  zipfebu01    1961
19351   ziskri01    1971
19352   zitoba01    2000
19353  zitzmbi01    1919
19354  zmiched01    1910
19355  zobribe01    2006
19356  zoccope01    2003
19357  zoldasa01    1944
19358  zoskyed01    1991
19359  zuberbi01    1936
19360  zuberjo01    1996
19361  zuletju01    2000
19362  zumayjo01    2006
19363  zuninmi01    2013
19364  zupcibo01    1991
19365   zupofr01    1957
19366  zuvelpa01    1982
19367  zuverge01    1951
19368  zwilldu01    1910
19369   zychto01    2015

[19370 rows x 2 columns]

### 2. Merge debut year into master data and calculate years of experience

In [27]:
# Now merge debut year into master data
Master = pd.merge(Master, Debut, on=['playerID'], how = 'left')
Master.head()

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,PA,OBP,SLG,BATAVG,SalYear,teamID,lgID,salary,lnSal,debutyr
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993

In [28]:
# Calculating years of experience

Master['Exp'] = Master['yearID'] - Master['debutyr'].astype(int)
Master.head()

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,OBP,SLG,BATAVG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019,1997,1
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538,1997,3
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150,1993,5
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363,1993,6
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685,1993,7

### 3. Based on a player’s years of experience, create indicator variables for arbitration eligible players (3-6 years) and free agent players (more than 6 years)

In [29]:
# Use experience as proxy to classify players contract status as arbitration eligible or free agent
Master['Arb'] = np.where((Master['Exp'] <= 6) & (Master['Exp'] >= 3),1,0)
Master['Free'] = np.where(Master['Exp'] > 6, 1, 0)
Master.head()

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,BATAVG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp,Arb,Free
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,0.278689,1999,CHA,AL,255000,12.449019,1997,1,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,0.274419,2001,FLO,NL,300000,12.611538,1997,3,1,0
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,0.262887,1999,COL,NL,900000,13.710150,1993,5,1,0
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,0.272727,2000,NYN,NL,500000,13.122363,1993,6,1,0
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,0.216561,2001,ATL,NL,600000,13.304685,1993,7,0,1

### 4. Read in the data for player appearances and group by stint.  Then identify the maximum number of games played at a given position for each year.

In [30]:
# Aggregate appearance data by stint using playerID and yearID

Appearances = Appearances.groupby(['playerID','yearID'])['G_c','G_1b','G_2b','G_3b','G_ss','G_of','G_dh'].sum()                                       
Appearances.reset_index(inplace=True)
display(Appearances)

# Note that we need to use 'reset.index' again

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh
0      aardsda01    2004    0     0     0     0     0     0   0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0
5      aardsda01    2010    0     0     0     0     0     0   0.0
6      aardsda01    2012    0     0     0     0     0     0   0.0
7      aardsda01    2013    0     0     0     0     0     0   0.0
8      aardsda01    2015    0     0     0     0     0     0   0.0
9      aaronha01    1954    0     0     0     0     0   116   0.0
10     aaronha01    1955    0     0    27     0     0   126   0.0
11     aaronha01    1956    0     0     0     0     0   152   0.0
12     aaronha01    1957    0     0     0     0     0   150   0.0
13     aaronha01    1958    0     0     0     0     0   153   0.0
14     aaronha01    1959    0     0     0     5     0   152   0.0
15     aaronha01    1960    0     0     2     0     0   153   0.0
16     aaronha01    1961    0     0     0     2     0   154   0.0
17     aaronha01    1962    0     1     0     0     0   153   0.0
18     aaronha01    1963    0     0     0     0     0   161   0.0
19     aaronha01    1964    0     0    11     0     0   139   0.0
20     aaronha01    1965    0     0     0     0     0   148   0.0
21     aaronha01    1966    0     0     2     0     0   158   0.0
22     aaronha01    1967    0     0     1     0     0   152   0.0
23     aaronha01    1968    0    14     0     0     0   151   0.0
24     aaronha01    1969    0     4     0     0     0   144   0.0
25     aaronha01    1970    0    11     0     0     0   125   0.0
26     aaronha01    1971    0    71     0     0     0    60   0.0
27     aaronha01    1972    0   109     0     0     0    15   0.0
28     aaronha01    1973    0     0     0     0     0   105   0.0
29     aaronha01    1974    0     0     0     0     0    89   0.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...
96582  zupcibo01    1992    0     0     0     0     0   114   5.0
96583  zupcibo01    1993    0     0     0     0     0   122   5.0
96584  zupcibo01    1994    0     1     0     2     0    30   1.0
96585   zupofr01    1957    8     0     0     0     0     0   0.0
96586   zupofr01    1958    1     0     0     0     0     0   0.0
96587   zupofr01    1961    4     0     0     0     0     0   0.0
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0
96597  zuverge01    1951    0     0     0     0     0     0   0.0
96598  zuverge01    1952    0     0     0     0     0     0   0.0
96599  zuverge01    1954    0     0     0     0     0     0   0.0
96600  zuverge01    1955    0     0     0     0     0     0   0.0
96601  zuverge01    1956    0     0     0     0     0     0   0.0
96602  zuverge01    1957    0     0     0     0     0     0   0.0
96603  zuverge01    1958    0     0     0     0     0     0   0.0
96604  zuverge01    1959    0     0     0     0     0     0   0.0
96605  zwilldu01    1910    0     0     0     0     0    27   0.0
96606  zwilldu01    1914    0     0     0     0     0   154   0.0
96607  zwilldu01    1915    0     3     0     0     0   148   0.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0
96609   zychto01    2015    0     0     0     0     0     0   0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0

[96612 rows x 9 columns]

In [31]:
# (i) Find max number of appearances for each position

Appearances['Max_G'] = Appearances[["G_c","G_1b","G_2b","G_3b","G_ss","G_of","G_dh"]].max(axis=1)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0
5      aardsda01    2010    0     0     0     0     0     0   0.0    0.0
6      aardsda01    2012    0     0     0     0     0     0   0.0    0.0
7      aardsda01    2013    0     0     0     0     0     0   0.0    0.0
8      aardsda01    2015    0     0     0     0     0     0   0.0    0.0
9      aaronha01    1954    0     0     0     0     0   116   0.0  116.0
10     aaronha01    1955    0     0    27     0     0   126   0.0  126.0
11     aaronha01    1956    0     0     0     0     0   152   0.0  152.0
12     aaronha01    1957    0     0     0     0     0   150   0.0  150.0
13     aaronha01    1958    0     0     0     0     0   153   0.0  153.0
14     aaronha01    1959    0     0     0     5     0   152   0.0  152.0
15     aaronha01    1960    0     0     2     0     0   153   0.0  153.0
16     aaronha01    1961    0     0     0     2     0   154   0.0  154.0
17     aaronha01    1962    0     1     0     0     0   153   0.0  153.0
18     aaronha01    1963    0     0     0     0     0   161   0.0  161.0
19     aaronha01    1964    0     0    11     0     0   139   0.0  139.0
20     aaronha01    1965    0     0     0     0     0   148   0.0  148.0
21     aaronha01    1966    0     0     2     0     0   158   0.0  158.0
22     aaronha01    1967    0     0     1     0     0   152   0.0  152.0
23     aaronha01    1968    0    14     0     0     0   151   0.0  151.0
24     aaronha01    1969    0     4     0     0     0   144   0.0  144.0
25     aaronha01    1970    0    11     0     0     0   125   0.0  125.0
26     aaronha01    1971    0    71     0     0     0    60   0.0   71.0
27     aaronha01    1972    0   109     0     0     0    15   0.0  109.0
28     aaronha01    1973    0     0     0     0     0   105   0.0  105.0
29     aaronha01    1974    0     0     0     0     0    89   0.0   89.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...
96582  zupcibo01    1992    0     0     0     0     0   114   5.0  114.0
96583  zupcibo01    1993    0     0     0     0     0   122   5.0  122.0
96584  zupcibo01    1994    0     1     0     2     0    30   1.0   30.0
96585   zupofr01    1957    8     0     0     0     0     0   0.0    8.0
96586   zupofr01    1958    1     0     0     0     0     0   0.0    1.0
96587   zupofr01    1961    4     0     0     0     0     0   0.0    4.0
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0    1.0
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0    2.0
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0    6.0
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0   42.0
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0   21.0
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0    7.0
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0   49.0
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0   15.0
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0    2.0
96597  zuverge01    1951    0     0     0     0     0     0   0.0    0.0
96598  zuverge01    1952    0     0     0     0     0     0   0.0    0.0
96599  zuverge01    1954    0     0     0     0     0     0   0.0    0.0
96600  zuverge01    1955    0     0     0     0     0     0   0.0    0.0
96601  zuverge01    1956    0     0     0     0     0     0   0.0    0.0
96602  zuverge01    1957    0     0     0     0     0     0   0.0    0.0
96603  zuverge01    1958    0     0     0     0     0     0   0.0    0.0
96604  zuverge01    1959    0     0     0     0     0     0   0.0    0.0
96605  zwilldu01    1910    0     0     0     0     0    27   0.0   27.0
96606  zwilldu01    1914    0     0     0     0     0   154   0.0  154.0
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0

[96612 rows x 10 columns]

### 5. Create a function to determine player position.

In [32]:
# (ii) Assign each player season to a primary position 

# Create definiton to position classification process
def Position(df):
    if (df['Max_G'] == df['G_c']): return "C"
    elif (df['Max_G'] == df['G_1b']): return "1B"
    elif (df['Max_G'] == df['G_2b']): return "2B"
    elif (df['Max_G'] == df['G_3b']): return "3B"
    elif (df['Max_G'] == df['G_ss']): return "SS"
    elif (df['Max_G'] == df['G_of']): return "OF"
    elif (df['Max_G'] == df['G_dh']): return "DH"

# Apply newly created definition to appearance data as variable 'POS'
Appearances['POS'] = Appearances.apply(Position, axis = 1)    

display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G POS
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0   C
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0   C
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0   C
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0   C
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0   C
5      aardsda01    2010    0     0     0     0     0     0   0.0    0.0   C
6      aardsda01    2012    0     0     0     0     0     0   0.0    0.0   C
7      aardsda01    2013    0     0     0     0     0     0   0.0    0.0   C
8      aardsda01    2015    0     0     0     0     0     0   0.0    0.0   C
9      aaronha01    1954    0     0     0     0     0   116   0.0  116.0  OF
10     aaronha01    1955    0     0    27     0     0   126   0.0  126.0  OF
11     aaronha01    1956    0     0     0     0     0   152   0.0  152.0  OF
12     aaronha01    1957    0     0     0     0     0   150   0.0  150.0  OF
13     aaronha01    1958    0     0     0     0     0   153   0.0  153.0  OF
14     aaronha01    1959    0     0     0     5     0   152   0.0  152.0  OF
15     aaronha01    1960    0     0     2     0     0   153   0.0  153.0  OF
16     aaronha01    1961    0     0     0     2     0   154   0.0  154.0  OF
17     aaronha01    1962    0     1     0     0     0   153   0.0  153.0  OF
18     aaronha01    1963    0     0     0     0     0   161   0.0  161.0  OF
19     aaronha01    1964    0     0    11     0     0   139   0.0  139.0  OF
20     aaronha01    1965    0     0     0     0     0   148   0.0  148.0  OF
21     aaronha01    1966    0     0     2     0     0   158   0.0  158.0  OF
22     aaronha01    1967    0     0     1     0     0   152   0.0  152.0  OF
23     aaronha01    1968    0    14     0     0     0   151   0.0  151.0  OF
24     aaronha01    1969    0     4     0     0     0   144   0.0  144.0  OF
25     aaronha01    1970    0    11     0     0     0   125   0.0  125.0  OF
26     aaronha01    1971    0    71     0     0     0    60   0.0   71.0  1B
27     aaronha01    1972    0   109     0     0     0    15   0.0  109.0  1B
28     aaronha01    1973    0     0     0     0     0   105   0.0  105.0  OF
29     aaronha01    1974    0     0     0     0     0    89   0.0   89.0  OF
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...  ..
96582  zupcibo01    1992    0     0     0     0     0   114   5.0  114.0  OF
96583  zupcibo01    1993    0     0     0     0     0   122   5.0  122.0  OF
96584  zupcibo01    1994    0     1     0     2     0    30   1.0   30.0  OF
96585   zupofr01    1957    8     0     0     0     0     0   0.0    8.0   C
96586   zupofr01    1958    1     0     0     0     0     0   0.0    1.0   C
96587   zupofr01    1961    4     0     0     0     0     0   0.0    4.0   C
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0    1.0  SS
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0    2.0  SS
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0    6.0  2B
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0   42.0  2B
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0   21.0  SS
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0    7.0  2B
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0   49.0  SS
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0   15.0  SS
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0    2.0  3B
96597  zuverge01    1951    0     0     0     0     0     0   0.0    0.0   C
96598  zuverge01    1952    0     0     0     0     0     0   0.0    0.0   C
96599  zuverge01    1954    0     0     0     0     0     0   0.0    0.0   C
96600  zuverge01    1955    0     0     0     0     0     0   0.0    0.0   C
96601  zuverge01    1956    0     0     0     0     0     0   0.0    0.0   C
96602  zuverge01    1957    0     0     0     0     0     0   0.0    0.0   C
96603  zuverge01    1958    0     0     0     0     0     0   0.0    0.0   C
96604  zuverge01    1959    0     0     0     0     0     0   0.0    0.0   C
96605  zwilldu01    1910    0     0     0     0     0    27   0.0   27.0  OF
96606  zwilldu01    1914    0     0     0     0     0   154   0.0  154.0  OF
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0  OF
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0  OF
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0   C
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0   C
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0   C

[96612 rows x 11 columns]

### 6. Exclude non-position players.

In [33]:
# Exclude non-position players (designated hitters) and keep necessary variables

Appearances = Appearances[Appearances['Max_G'] > 0] 
Appearances = Appearances[['playerID','yearID','POS']]
display(Appearances)

        playerID  yearID POS
9      aaronha01    1954  OF
10     aaronha01    1955  OF
11     aaronha01    1956  OF
12     aaronha01    1957  OF
13     aaronha01    1958  OF
14     aaronha01    1959  OF
15     aaronha01    1960  OF
16     aaronha01    1961  OF
17     aaronha01    1962  OF
18     aaronha01    1963  OF
19     aaronha01    1964  OF
20     aaronha01    1965  OF
21     aaronha01    1966  OF
22     aaronha01    1967  OF
23     aaronha01    1968  OF
24     aaronha01    1969  OF
25     aaronha01    1970  OF
26     aaronha01    1971  1B
27     aaronha01    1972  1B
28     aaronha01    1973  OF
29     aaronha01    1974  OF
30     aaronha01    1975  DH
31     aaronha01    1976  DH
32     aaronto01    1962  1B
33     aaronto01    1963  1B
34     aaronto01    1965  1B
35     aaronto01    1968  OF
36     aaronto01    1969  1B
37     aaronto01    1970  1B
38     aaronto01    1971  1B
...          ...     ...  ..
96554  zoskyed01    1999  3B
96567  zuberjo01    1996  1B
96568  zuberjo01    1998  OF
96569  zuletju01    2000  1B
96570  zuletju01    2001  1B
96576  zuninmi01    2013   C
96577  zuninmi01    2014   C
96578  zuninmi01    2015   C
96579  zuninmi01    2016   C
96580  zuninmi01    2017   C
96581  zupcibo01    1991  OF
96582  zupcibo01    1992  OF
96583  zupcibo01    1993  OF
96584  zupcibo01    1994  OF
96585   zupofr01    1957   C
96586   zupofr01    1958   C
96587   zupofr01    1961   C
96588  zuvelpa01    1982  SS
96589  zuvelpa01    1983  SS
96590  zuvelpa01    1984  2B
96591  zuvelpa01    1985  2B
96592  zuvelpa01    1986  SS
96593  zuvelpa01    1987  2B
96594  zuvelpa01    1988  SS
96595  zuvelpa01    1989  SS
96596  zuvelpa01    1991  3B
96605  zwilldu01    1910  OF
96606  zwilldu01    1914  OF
96607  zwilldu01    1915  OF
96608  zwilldu01    1916  OF

[55969 rows x 3 columns]

### 7. Create an indicator variable for catcher and the infield (2B, SS, 3B) positions separately. Thus, you should have a separate indicator variable for 2B, SS, and 3B individually as opposed to one infielder indicator variable combining these positions.

In [34]:
# Create a indicator variable for catcher and infielder (2B, 3B, SS)

Appearances['Catch'] = np.where(Appearances['POS'] == "C", 1, 0)
Appearances['Infld'] = np.where((Appearances['POS'] == "2B") | (Appearances['POS'] == "3B") | 
                                (Appearances['POS'] == "SS"), 1, 0)

display(Appearances)

        playerID  yearID POS  Catch  Infld
9      aaronha01    1954  OF      0      0
10     aaronha01    1955  OF      0      0
11     aaronha01    1956  OF      0      0
12     aaronha01    1957  OF      0      0
13     aaronha01    1958  OF      0      0
14     aaronha01    1959  OF      0      0
15     aaronha01    1960  OF      0      0
16     aaronha01    1961  OF      0      0
17     aaronha01    1962  OF      0      0
18     aaronha01    1963  OF      0      0
19     aaronha01    1964  OF      0      0
20     aaronha01    1965  OF      0      0
21     aaronha01    1966  OF      0      0
22     aaronha01    1967  OF      0      0
23     aaronha01    1968  OF      0      0
24     aaronha01    1969  OF      0      0
25     aaronha01    1970  OF      0      0
26     aaronha01    1971  1B      0      0
27     aaronha01    1972  1B      0      0
28     aaronha01    1973  OF      0      0
29     aaronha01    1974  OF      0      0
30     aaronha01    1975  DH      0      0
31     aaronha01    1976  DH      0      0
32     aaronto01    1962  1B      0      0
33     aaronto01    1963  1B      0      0
34     aaronto01    1965  1B      0      0
35     aaronto01    1968  OF      0      0
36     aaronto01    1969  1B      0      0
37     aaronto01    1970  1B      0      0
38     aaronto01    1971  1B      0      0
...          ...     ...  ..    ...    ...
96554  zoskyed01    1999  3B      0      1
96567  zuberjo01    1996  1B      0      0
96568  zuberjo01    1998  OF      0      0
96569  zuletju01    2000  1B      0      0
96570  zuletju01    2001  1B      0      0
96576  zuninmi01    2013   C      1      0
96577  zuninmi01    2014   C      1      0
96578  zuninmi01    2015   C      1      0
96579  zuninmi01    2016   C      1      0
96580  zuninmi01    2017   C      1      0
96581  zupcibo01    1991  OF      0      0
96582  zupcibo01    1992  OF      0      0
96583  zupcibo01    1993  OF      0      0
96584  zupcibo01    1994  OF      0      0
96585   zupofr01    1957   C      1      0
96586   zupofr01    1958   C      1      0
96587   zupofr01    1961   C      1      0
96588  zuvelpa01    1982  SS      0      1
96589  zuvelpa01    1983  SS      0      1
96590  zuvelpa01    1984  2B      0      1
96591  zuvelpa01    1985  2B      0      1
96592  zuvelpa01    1986  SS      0      1
96593  zuvelpa01    1987  2B      0      1
96594  zuvelpa01    1988  SS      0      1
96595  zuvelpa01    1989  SS      0      1
96596  zuvelpa01    1991  3B      0      1
96605  zwilldu01    1910  OF      0      0
96606  zwilldu01    1914  OF      0      0
96607  zwilldu01    1915  OF      0      0
96608  zwilldu01    1916  OF      0      0

[55969 rows x 5 columns]

### 8. Merge this into your master data.

In [35]:
# Merge position data into Master data

Master = pd.merge(Master, Appearances, on=['playerID','yearID'], how = 'left')
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,lgID,salary,lnSal,debutyr,Exp,Arb,Free,POS,Catch,Infld
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,AL,255000,12.449019,1997,1,0,0,OF,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,NL,300000,12.611538,1997,3,1,0,OF,0,0
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,NL,900000,13.710150,1993,5,1,0,SS,0,1
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,NL,500000,13.122363,1993,6,1,0,2B,0,1
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,NL,600000,13.304685,1993,7,0,1,SS,0,1
5,abernbr01,2001,1,79,304,43,82,17,1,5,...,AL,215000,12.278393,2001,0,0,0,2B,0,1
6,abernbr01,2002,1,117,463,46,112,18,4,2,...,AL,300000,12.611538,2001,1,0,0,2B,0,1
7,abreubo01,1998,1,151,497,68,155,29,6,17,...,NL,400000,12.899220,1996,2,0,0,OF,0,0
8,abreubo01,1999,1,152,546,118,183,35,11,20,...,NL,2933333,14.891650,1996,3,1,0,OF,0,0
9,abreubo01,2000,1,154,576,103,182,42,10,25,...,NL,4983000,15.421543,1996,4,1,0,OF,0,0
10,abreubo01,2001,1,162,588,118,170,48,4,31,...,NL,6333333,15.661337,1996,5,1,0,OF,0,0
11,abreubo01,2002,1,157,572,102,176,50,6,20,...,NL,9100000,16.023785,1996,6,1,0,OF,0,0
12,abreubo01,2003,1,158,577,99,173,35,1,20,...,NL,10600000,16.176365,1996,7,0,1,OF,0,0
13,abreubo01,2004,1,159,574,118,173,47,1,30,...,NL,13100000,16.388123,1996,8,0,1,OF,0,0
14,abreubo01,2005,1,162,588,104,168,37,1,24,...,NL,13600000,16.425580,1996,9,0,1,OF,0,0
15,abreubo01,2006,3,156,548,98,163,41,2,15,...,AL,15000000,16.523561,1996,10,0,1,OF,0,0
16,adamsru01,2005,1,139,481,68,123,27,5,8,...,AL,343000,12.745486,2004,1,0,0,SS,0,1
17,agbaybe01,1999,1,101,276,42,79,18,3,14,...,NL,220000,12.301383,1998,1,0,0,OF,0,0
18,agbaybe01,2000,1,119,350,59,101,19,1,15,...,NL,260000,12.468437,1998,2,0,0,OF,0,0
19,agbaybe01,2001,1,91,296,28,82,14,2,6,...,NL,600000,13.304685,1998,3,1,0,OF,0,0
20,alexama02,1998,1,108,264,34,60,10,1,5,...,NL,475000,13.071070,1992,6,1,0,SS,0,1
21,alexama02,1999,1,90,177,17,48,11,2,0,...,AL,612500,13.325304,1992,7,0,1,SS,0,1
22,alfoned01,1998,1,144,557,94,155,28,2,17,...,NL,2800000,14.845130,1995,3,1,0,3B,0,1
23,alfoned01,1999,1,158,628,123,191,41,1,27,...,NL,4225000,15.256530,1995,4,1,0,2B,0,1
24,alfoned01,2000,1,150,544,109,176,40,2,25,...,NL,5750000,15.564710,1995,5,1,0,2B,0,1
25,alfoned01,2001,1,124,457,64,111,22,0,17,...,NL,6200000,15.640060,1995,6,1,0,2B,0,1
26,alfoned01,2002,1,135,490,78,151,26,0,16,...,NL,4000000,15.201805,1995,7,0,1,3B,0,1
27,alfoned01,2003,1,142,514,56,133,25,2,13,...,NL,6500000,15.687313,1995,8,0,1,3B,0,1
28,alfoned01,2004,1,139,519,66,150,26,1,11,...,NL,7500000,15.830414,1995,9,0,1,3B,0,1
29,alfoned01,2005,1,109,368,36,102,17,1,2,...,AL,8000000,15.894952,1995,10,0,1,3B,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3084,younger01,2000,1,153,607,98,180,40,2,6,...,NL,4500000,15.319588,1992,8,0,1,2B,0,1
3085,younger01,2001,1,149,603,98,168,43,4,6,...,NL,2000000,14.508658,1992,9,0,1,2B,0,1
3086,younger01,2002,1,138,496,57,139,29,3,3,...,NL,2000000,14.508658,1992,10,0,1,2B,0,1
3087,younger01,2003,3,135,475,80,119,20,1,15,...,AL,1000000,13.815511,1992,11,0,1,2B,0,1
3088,younger01,2004,1,104,344,55,99,25,2,1,...,NL,850000,13.652992,1992,12,0,1,OF,0,0
3089,younger01,2005,1,56,142,22,39,9,0,2,...,NL,700000,13.458836,1992,13,0,1,OF,0,0
3090,youngke01,1998,1,159,592,88,160,40,2,27,...,NL,2100000,14.557448,1992,6,1,0,1B,0,0
3091,youngke01,1999,1,156,584,103,174,41,6,26,...,NL,5625000,15.542732,1992,7,0,1,1B,0,0
3092,youngke01,2000,1,132,496,77,128,27,0,20,...,NL,6125000,15.627889,1992,8,0,1,1B,0,0
3093,youngke01,2001,1,142,449,53,104,33,0,14,...,NL,5625000,15.542732,1992,9,0,1,1B,0,0
3094,youngke01,2002,1,146,468,60,115,26,1,16,...,NL,6625000,15.706361,1992,10,0,1,1B,0,0
3095,youngmi02,2001,1,106,386,57,96,18,4,11,...,AL,250000,12.429216,2000,1,0,0,2B,0,1
3096,youngmi02,2002,1,156,573,77,150,26,8,9,...,AL,415000,12.936034,2000,2,0,0,2B,0,1
3097,youngmi02,2003,1,160,666,106,204,33,9,14,...,AL,450000,13.017003,2000,3,1,0,2B,0,1
3098,youngmi02,2004,1,160,690,114,216,33,9,22,...,AL,2575000,14.761360,2000,4,1,0,SS,0,1
3099,youngmi02,2005,1,159,668,114,221,40,5,24,...,AL,3075000,14.938815,2000,5,1,0,SS,0,1
3100,youngmi02,2006,1,162,691,93,217,52,3,14,...,AL,3575000,15.089476,2000,6,1,0,SS,0,1
3101,zaungr01,1998,1,106,298,19,56,12,2,5,...,AL,450000,13.017003,1995,3,1,0,C,1,0
3102,zaungr01,2000,1,83,234,36,64,11,0,7,...,AL,1150000,13.955273,1995,5,1,0,C,1,0
3103,zaungr01,2002,1,76,185,18,41,7,1,3,...,NL,1200000,13.997832,1995,7,0,1,C,1,0
3104,zaungr01,2004,1,107,338,46,91,24,0,6,...,AL,950000,13.764217,1995,9,0,1,C,1,0
3105,zaungr01,2005,1,133,434,61,109,18,1,11,...,AL,1000000,13.815511,1995,10,0,1,C,1,0
3106,zaungr01,2006,1,99,290,39,79,19,0,12,...,AL,3500000,15.068274,1995,11,0,1,C,1,0
3107,zeileto01,1998,6,158,572,85,155,32,3,19,...,AL,3200000,14.978661,1989,9,0,1,3B,0,1
3108,zeileto01,1999,1,156,588,80,172,41,1,24,...,NL,4333333,15.281848,1989,10,0,1,3B,0,1
3109,zeileto01,2000,1,153,544,67,146,36,3,22,...,NL,6833333,15.737323,1989,11,0,1,1B,0,0
3110,zeileto01,2001,1,151,531,66,141,25,1,10,...,NL,6833333,15.737323,1989,12,0,1,1B,0,0
3111,zeileto01,2002,1,144,506,61,138,23,0,18,...,AL,1500000,14.220976,1989,13,0,1,3B,0,1
3112,zeileto01,2003,3,100,299,40,68,10,2,11,...,NL,1000000,13.815511,1989,14,0,1,3B,0,1
3113,zobribe01,2006,1,52,183,10,41,6,2,2,...,AL,383400,12.856834,2006,0,0,0,SS,0,1

In [39]:
Quiz2_2 = Master[(Master['Arb'] == 1) | (Master['Free'] == 1)]
Quiz2_2.shape

(2454, 36)

In [40]:
Master.shape

(3114, 36)

In [41]:
2454/3114

0.7880539499036608

In [42]:
Master.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['playerID', 'yearID', 'stint', 'G', 'AB', 'R', 'H', 'Doubles',
       'Triples', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH',
       'SF', 'GIDP', 'PA', 'OBP', 'SLG', 'BATAVG', 'SalYear', 'teamID', 'lgID',
       'salary', 'lnSal', 'debutyr', 'Exp', 'Arb', 'Free', 'POS', 'Catch',
       'Infld'],
      dtype='object')>

In [45]:
Quiz2_3 = Master.groupby(['yearID'])[['Exp']].sum() 
Quiz2_3

         Exp
yearID
1998    2112
1999    2116
2000    2228
2001    2149
2002    2164
2003    2190
2004    2140
2005    2093
2006    2132

# III. Running Regressions

### 1. lnSal on OBP, SLG, batting average, plate appearances, arbitration (dummy), free agent (dummy), and all positional dummy variables during the seasons prior to the publication of Moneyball (1999-2003) combined.

In [48]:
import statsmodels.formula.api as smf
Master1 = Master[(Master.SalYear >= 1999) & (Master.SalYear <= 2003)]
Val_All_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BATAVG + PA + Arb + Free + Catch + Infld', data=Master1).fit()
Val_All_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.691
Model:                            OLS   Adj. R-squared:                  0.689
Method:                 Least Squares   F-statistic:                     486.6
Date:                Sat, 27 May 2023   Prob (F-statistic):               0.00
Time:                        06:04:20   Log-Likelihood:                -1858.3
No. Observations:                1753   AIC:                             3735.
Df Residuals:                    1744   BIC:                             3784.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.3702      0.164     63.101      0.000      10.048      10.693
OBP            1.4281      0.702      2.035      0.042       0.052       2.805
SLG            2.9637      0.314      9.446      0.000       2.348       3.579
BATAVG        -2.1911      0.886     -2.472      0.014      -3.929      -0.453
PA             0.0031      0.000     27.456      0.000       0.003       0.003
Arb            1.2487      0.046     26.879      0.000       1.158       1.340
Free           1.8202      0.046     39.163      0.000       1.729       1.911
Catch          0.1156      0.054      2.155      0.031       0.010       0.221
Infld          0.0084      0.039      0.215      0.830      -0.068       0.085
==============================================================================
Omnibus:                       11.924   Durbin-Watson:                   1.404
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               16.814
Skew:                          -0.022   Prob(JB):                     0.000223
Kurtosis:                       3.478   Cond. No.                     2.90e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.9e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### 2. Repeat step 2) but run the regression for the seasons 2004-2006 (all years combined).

In [49]:
Master2 = Master[(Master.SalYear >= 2004) & (Master.SalYear <= 2006)]
Val_All2_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + BATAVG + PA + Arb + Free + Catch + Infld', data=Master2).fit()
Val_All2_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.624
Model:                            OLS   Adj. R-squared:                  0.621
Method:                 Least Squares   F-statistic:                     209.2
Date:                Sat, 27 May 2023   Prob (F-statistic):          3.03e-208
Time:                        06:05:32   Log-Likelihood:                -1175.3
No. Observations:                1018   AIC:                             2369.
Df Residuals:                    1009   BIC:                             2413.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.0510      0.262     38.349      0.000       9.537      10.565
OBP            5.4004      1.079      5.005      0.000       3.283       7.518
SLG            2.9324      0.473      6.195      0.000       2.004       3.861
BATAVG        -4.7271      1.331     -3.552      0.000      -7.339      -2.116
PA             0.0030      0.000     17.650      0.000       0.003       0.003
Arb            1.0976      0.068     16.130      0.000       0.964       1.231
Free           1.6842      0.066     25.648      0.000       1.555       1.813
Catch          0.0947      0.078      1.218      0.224      -0.058       0.247
Infld         -0.0277      0.056     -0.492      0.623      -0.138       0.083
==============================================================================
Omnibus:                       12.279   Durbin-Watson:                   1.388
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               15.726
Skew:                           0.151   Prob(JB):                     0.000385
Kurtosis:                       3.529   Cond. No.                     3.07e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.07e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
#Uncomment this cell once the assignment is complete in order to export your Master dataset
#Master.to_csv("../Data/Master.csv")